<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Medicine;
use Carbon\Carbon;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Парацетамол',
                'description' => 'Жаропонижающее и обезболивающее средство',
                'price' => 150.00,
                'quantity' => 50,
                'category' => 'Жаропонижающие',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(24),
            ],
            [
                'name' => 'Ибупрофен',
                'description' => 'Противовоспалительное и обезболивающее',
                'price' => 180.00,
                'quantity' => 35,
                'category' => 'Противовоспалительные',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(18),
            ],
            [
                'name' => 'Аспирин',
                'description' => 'Антиагрегант, жаропонижающее',
                'price' => 120.00,
                'quantity' => 60,
                'category' => 'Кардиология',
                'manufacturer' => 'Байер',
                'expiry_date' => Carbon::now()->addMonths(30),
            ],
            [
                'name' => 'Амоксициллин',
                'description' => 'Антибиотик широкого спектра действия',
                'price' => 250.00,
                'quantity' => 25,
                'category' => 'Антибиотики',
                'manufacturer' => 'Сандоз',
                'expiry_date' => Carbon::now()->addMonths(12),
            ],
            [
                'name' => 'Лоратадин',
                'description' => 'Противоаллергическое средство',
                'price' => 200.00,
                'quantity' => 40,
                'category' => 'Антигистаминные',
                'manufacturer' => 'Акрихин',
                'expiry_date' => Carbon::now()->addMonths(20),
            ],
            [
                'name' => 'Омепразол',
                'description' => 'Ингибитор протонной помпы',
                'price' => 220.00,
                'quantity' => 30,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Омез',
                'expiry_date' => Carbon::now()->addMonths(15),
            ],
            [
                'name' => 'Амоксиклав',
                'description' => 'Комбинированный антибиотик',
                'price' => 350.00,
                'quantity' => 20,
                'category' => 'Антибиотики',
                'manufacturer' => 'Лек',
                'expiry_date' => Carbon::now()->addMonths(14),
            ],
            [
                'name' => 'Цитрамон',
                'description' => 'Комбинированное обезболивающее',
                'price' => 95.00,
                'quantity' => 70,
                'category' => 'Обезболивающие',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(22),
            ],
            [
                'name' => 'Но-шпа',
                'description' => 'Спазмолитическое средство',
                'price' => 280.00,
                'quantity' => 45,
                'category' => 'Спазмолитики',
                'manufacturer' => 'Санофи',
                'expiry_date' => Carbon::now()->addMonths(16),
            ],
            [
                'name' => 'Активированный уголь',
                'description' => 'Адсорбент при отравлениях',
                'price' => 80.00,
                'quantity' => 100,
                'category' => 'Адсорбенты',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(36),
            ],
            [
                'name' => 'Називин',
                'description' => 'Сосудосуживающее средство для носа',
                'price' => 160.00,
                'quantity' => 55,
                'category' => 'Отоларингология',
                'manufacturer' => 'Никомед',
                'expiry_date' => Carbon::now()->addMonths(18),
            ],
            [
                'name' => 'Смекта',
                'description' => 'Противодиарейное средство',
                'price' => 190.00,
                'quantity' => 42,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Ипсен',
                'expiry_date' => Carbon::now()->addMonths(24),
            ],
            [
                'name' => 'Нурофен',
                'description' => 'Противовоспалительное и обезболивающее',
                'price' => 210.00,
                'quantity' => 38,
                'category' => 'Противовоспалительные',
                'manufacturer' => 'Рекитт Бенкизер',
                'expiry_date' => Carbon::now()->addMonths(20),
            ],
            [
                'name' => 'Супрастин',
                'description' => 'Антигистаминное средство',
                'price' => 140.00,
                'quantity' => 48,
                'category' => 'Антигистаминные',
                'manufacturer' => 'Эгис',
                'expiry_date' => Carbon::now()->addMonths(16),
            ],
            [
                'name' => 'Валидол',
                'description' => 'Успокаивающее средство',
                'price' => 75.00,
                'quantity' => 85,
                'category' => 'Кардиология',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(28),
            ],
            [
                'name' => 'Азитромицин',
                'description' => 'Антибиотик широкого спектра',
                'price' => 320.00,
                'quantity' => 22,
                'category' => 'Антибиотики',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(13),
            ],
            [
                'name' => 'Анальгин',
                'description' => 'Обезболивающее и жаропонижающее',
                'price' => 110.00,
                'quantity' => 65,
                'category' => 'Обезболивающие',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(26),
            ],
            [
                'name' => 'Папаверин',
                'description' => 'Спазмолитическое средство',
                'price' => 95.00,
                'quantity' => 58,
                'category' => 'Спазмолитики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(21),
            ],
            [
                'name' => 'Энтеросгель',
                'description' => 'Энтеросорбент',
                'price' => 380.00,
                'quantity' => 28,
                'category' => 'Адсорбенты',
                'manufacturer' => 'Силма',
                'expiry_date' => Carbon::now()->addMonths(19),
            ],
            [
                'name' => 'Терафлю',
                'description' => 'Комбинированное средство от простуды',
                'price' => 290.00,
                'quantity' => 33,
                'category' => 'Жаропонижающие',
                'manufacturer' => 'Новартис',
                'expiry_date' => Carbon::now()->addMonths(17),
            ],
            [
                'name' => 'Цетрин',
                'description' => 'Антигистаминное средство',
                'price' => 240.00,
                'quantity' => 36,
                'category' => 'Антигистаминные',
                'manufacturer' => 'Д-р Реддис',
                'expiry_date' => Carbon::now()->addMonths(22),
            ],
            [
                'name' => 'Ренни',
                'description' => 'Антацидное средство',
                'price' => 170.00,
                'quantity' => 52,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Байер',
                'expiry_date' => Carbon::now()->addMonths(25),
            ],
            [
                'name' => 'Кларитин',
                'description' => 'Антигистаминное средство',
                'price' => 270.00,
                'quantity' => 31,
                'category' => 'Антигистаминные',
                'manufacturer' => 'Шеринг-Плау',
                'expiry_date' => Carbon::now()->addMonths(18),
            ],
            [
                'name' => 'Фурацилин',
                'description' => 'Антисептическое средство',
                'price' => 130.00,
                'quantity' => 47,
                'category' => 'Антисептики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(23),
            ],
            [
                'name' => 'Мирамистин',
                'description' => 'Антисептик широкого спектра',
                'price' => 260.00,
                'quantity' => 39,
                'category' => 'Антисептики',
                'manufacturer' => 'Инфамед',
                'expiry_date' => Carbon::now()->addMonths(20),
            ],
            [
                'name' => 'Гексорал',
                'description' => 'Антисептик для горла',
                'price' => 310.00,
                'quantity' => 27,
                'category' => 'Отоларингология',
                'manufacturer' => 'Джонсон & Джонсон',
                'expiry_date' => Carbon::now()->addMonths(15),
            ],
            [
                'name' => 'Стрепсилс',
                'description' => 'Антисептик для горла',
                'price' => 185.00,
                'quantity' => 44,
                'category' => 'Отоларингология',
                'manufacturer' => 'Рекитт Бенкизер',
                'expiry_date' => Carbon::now()->addMonths(19),
            ],
            [
                'name' => 'Амоксициллин-Тева',
                'description' => 'Антибиотик пенициллинового ряда',
                'price' => 230.00,
                'quantity' => 29,
                'category' => 'Антибиотики',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(14),
            ],
            [
                'name' => 'Кеторол',
                'description' => 'Сильное обезболивающее',
                'price' => 195.00,
                'quantity' => 41,
                'category' => 'Обезболивающие',
                'manufacturer' => 'Д-р Реддис',
                'expiry_date' => Carbon::now()->addMonths(17),
            ],
            [
                'name' => 'Дротаверин',
                'description' => 'Спазмолитик',
                'price' => 105.00,
                'quantity' => 61,
                'category' => 'Спазмолитики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(24),
            ],
            [
                'name' => 'Аллохол',
                'description' => 'Желчегонное средство',
                'price' => 125.00,
                'quantity' => 56,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(27),
            ],
            [
                'name' => 'Корвалол',
                'description' => 'Успокаивающее и сосудорасширяющее',
                'price' => 90.00,
                'quantity' => 72,
                'category' => 'Кардиология',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(29),
            ],
            [
                'name' => 'Валерьянка',
                'description' => 'Успокаивающее средство',
                'price' => 70.00,
                'quantity' => 88,
                'category' => 'Успокоительные',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(32),
            ],
            [
                'name' => 'Персен',
                'description' => 'Успокаивающее средство',
                'price' => 340.00,
                'quantity' => 24,
                'category' => 'Успокоительные',
                'manufacturer' => 'Лек',
                'expiry_date' => Carbon::now()->addMonths(16),
            ],
            [
                'name' => 'Ново-Пассит',
                'description' => 'Успокаивающее средство',
                'price' => 360.00,
                'quantity' => 23,
                'category' => 'Успокоительные',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(18),
            ],
            [
                'name' => 'Афобазол',
                'description' => 'Анксиолитик',
                'price' => 420.00,
                'quantity' => 19,
                'category' => 'Успокоительные',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(15),
            ],
            [
                'name' => 'Аскорбиновая кислота',
                'description' => 'Витамин C',
                'price' => 65.00,
                'quantity' => 95,
                'category' => 'Витамины',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(34),
            ],
            [
                'name' => 'Компливит',
                'description' => 'Поливитаминный комплекс',
                'price' => 280.00,
                'quantity' => 34,
                'category' => 'Витамины',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(21),
            ],
            [
                'name' => 'Витрум',
                'description' => 'Поливитаминный комплекс',
                'price' => 450.00,
                'quantity' => 18,
                'category' => 'Витамины',
                'manufacturer' => 'Юнифарм',
                'expiry_date' => Carbon::now()->addMonths(19),
            ],
            [
                'name' => 'Алфавит',
                'description' => 'Поливитаминный комплекс',
                'price' => 320.00,
                'quantity' => 26,
                'category' => 'Витамины',
                'manufacturer' => 'Аквион',
                'expiry_date' => Carbon::now()->addMonths(22),
            ],
            [
                'name' => 'Цефтриаксон',
                'description' => 'Антибиотик цефалоспоринового ряда',
                'price' => 180.00,
                'quantity' => 37,
                'category' => 'Антибиотики',
                'manufacturer' => 'Сандоз',
                'expiry_date' => Carbon::now()->addMonths(12),
            ],
            [
                'name' => 'Левомицетин',
                'description' => 'Антибиотик широкого спектра',
                'price' => 145.00,
                'quantity' => 43,
                'category' => 'Антибиотики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(13),
            ],
            [
                'name' => 'Тетрациклин',
                'description' => 'Антибиотик тетрациклинового ряда',
                'price' => 165.00,
                'quantity' => 40,
                'category' => 'Антибиотики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(11),
            ],
            [
                'name' => 'Нимесил',
                'description' => 'Противовоспалительное средство',
                'price' => 330.00,
                'quantity' => 30,
                'category' => 'Противовоспалительные',
                'manufacturer' => 'Берлин-Хеми',
                'expiry_date' => Carbon::now()->addMonths(16),
            ],
            [
                'name' => 'Диклофенак',
                'description' => 'Противовоспалительное и обезболивающее',
                'price' => 155.00,
                'quantity' => 46,
                'category' => 'Противовоспалительные',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(17),
            ],
            [
                'name' => 'Мелоксикам',
                'description' => 'Противовоспалительное средство',
                'price' => 205.00,
                'quantity' => 35,
                'category' => 'Противовоспалительные',
                'manufacturer' => 'Тева',
                'expiry_date' => Carbon::now()->addMonths(15),
            ],
            [
                'name' => 'Темпалгин',
                'description' => 'Комбинированное обезболивающее',
                'price' => 175.00,
                'quantity' => 49,
                'category' => 'Обезболивающие',
                'manufacturer' => 'Актавис',
                'expiry_date' => Carbon::now()->addMonths(20),
            ],
            [
                'name' => 'Пенталгин',
                'description' => 'Комбинированное обезболивающее',
                'price' => 225.00,
                'quantity' => 32,
                'category' => 'Обезболивающие',
                'manufacturer' => 'Фармстандарт',
                'expiry_date' => Carbon::now()->addMonths(18),
            ],
            [
                'name' => 'Спазмалгон',
                'description' => 'Комбинированное спазмолитическое',
                'price' => 200.00,
                'quantity' => 38,
                'category' => 'Спазмолитики',
                'manufacturer' => 'Балканфарма',
                'expiry_date' => Carbon::now()->addMonths(19),
            ],
            [
                'name' => 'Бесалол',
                'description' => 'Спазмолитик и антисептик',
                'price' => 115.00,
                'quantity' => 54,
                'category' => 'Спазмолитики',
                'manufacturer' => 'Обновление',
                'expiry_date' => Carbon::now()->addMonths(23),
            ],
            [
                'name' => 'Фестал',
                'description' => 'Ферментное средство',
                'price' => 245.00,
                'quantity' => 33,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Санофи',
                'expiry_date' => Carbon::now()->addMonths(20),
            ],
            [
                'name' => 'Мезим',
                'description' => 'Ферментное средство',
                'price' => 265.00,
                'quantity' => 31,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Берлин-Хеми',
                'expiry_date' => Carbon::now()->addMonths(21),
            ],
            [
                'name' => 'Креон',
                'description' => 'Ферментное средство',
                'price' => 480.00,
                'quantity' => 17,
                'category' => 'Гастроэнтерология',
                'manufacturer' => 'Эбботт',
                'expiry_date' => Carbon::now()->addMonths(16),
            ],
        ];

        foreach ($medicines as $medicine) {
            Medicine::create($medicine);
        }
    }
}

